# Generated by Django 3.1.3 on 2020-12-14 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_idx', models.IntegerField(blank=True)),
                ('user_name', models.CharField(blank=True, max_length=50)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('pub_date', models.DateField()),
                ('text', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['doc_idx'],
            },
        ),
        migrations.CreateModel(
            name='RegionTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cluster_idx', models.IntegerField(default=-1)),
                ('topic_idx', models.IntegerField(default=None, null=True)),
                ('topic_prob', models.FloatField(blank=True, default=None, null=True)),
            ],
            options={
                'ordering': ['cluster_idx'],
            },
        ),
        migrations.CreateModel(
            name='TopicWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(blank=True, max_length=50)),
                ('keyword_prob', models.FloatField(blank=True, default=None, null=True)),
                ('c_t_idx', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='text.regiontopic')),
            ],
        ),
        migrations.CreateModel(
            name='DocWeatherEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(blank=True, max_length=30)),
                ('doc_idx', models.ManyToManyField(blank=True, to='text.Document')),
            ],
        ),
        migrations.AddField(
            model_name='document',
            name='cluster_idx',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='text.regiontopic'),
        ),
    ]
