# Generated by Django 3.1.3 on 2021-02-11 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
