# Generated by Django 3.1.3 on 2021-04-13 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geo_map', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='geotweet',
            old_name='geo_location',
            new_name='geo_id',
        ),
    ]
