# Generated by Django 3.1.3 on 2021-04-13 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geo_map', '0002_auto_20210413_1618'),
    ]

    operations = [
        migrations.RenameField(
            model_name='geotweet',
            old_name='geo_id',
            new_name='geo_location',
        ),
    ]
