# Generated by Django 3.1.3 on 2021-04-13 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geo_map', '0004_remove_geolocation_geo_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geotweet',
            name='tweet_id',
        ),
    ]
