# Generated by Django 3.1.3 on 2021-04-14 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geo_map', '0005_remove_geotweet_tweet_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GeoCache',
        ),
    ]
