# Generated by Django 3.1.3 on 2020-12-01 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo_map', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_idx', models.IntegerField(blank=True)),
                ('user_name', models.CharField(blank=True, max_length=50)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('pub_date', models.DateField()),
                ('text', models.TextField(blank=True)),
            ],
        ),
    ]
