# Generated by Django 3.1.3 on 2020-12-01 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo_map', '0003_testing'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Testing',
        ),
        migrations.RemoveField(
            model_name='data',
            name='doc_idx',
        ),
        migrations.RemoveField(
            model_name='data',
            name='pub_date',
        ),
        migrations.RemoveField(
            model_name='data',
            name='text',
        ),
        migrations.RemoveField(
            model_name='data',
            name='user_name',
        ),
        migrations.AddField(
            model_name='data',
            name='anger_score',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='confusion_score',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='disgust_score',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='fear_score',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='happiness_score',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='overall_score',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='sadness_score',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='shame_score',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='surprise_score',
            field=models.IntegerField(null=True),
        ),
    ]
