# Generated by Django 3.1.3 on 2020-12-04 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo_map', '0005_testing'),
    ]

    operations = [
        migrations.AddField(
            model_name='testing',
            name='search_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
