# Generated by Django 3.1.3 on 2020-12-04 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geo_map', '0006_testing_search_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='testing',
            new_name='search_history',
        ),
    ]
