# Generated by Django 3.1.3 on 2020-12-07 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geo_map', '0007_auto_20201204_1900'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Data',
            new_name='GeoData',
        ),
    ]
