# Generated by Django 3.1.3 on 2020-12-07 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo_map', '0008_auto_20201207_1516'),
    ]

    operations = [
        migrations.DeleteModel(
            name='search_history',
        ),
        migrations.RemoveField(
            model_name='tweetsperday',
            name='day',
        ),
        migrations.RemoveField(
            model_name='geodata',
            name='anger_score',
        ),
        migrations.RemoveField(
            model_name='geodata',
            name='confusion_score',
        ),
        migrations.RemoveField(
            model_name='geodata',
            name='disgust_score',
        ),
        migrations.RemoveField(
            model_name='geodata',
            name='fear_score',
        ),
        migrations.RemoveField(
            model_name='geodata',
            name='happiness_score',
        ),
        migrations.RemoveField(
            model_name='geodata',
            name='overall_score',
        ),
        migrations.RemoveField(
            model_name='geodata',
            name='sadness_score',
        ),
        migrations.RemoveField(
            model_name='geodata',
            name='shame_score',
        ),
        migrations.RemoveField(
            model_name='geodata',
            name='surprise_score',
        ),
        migrations.AddField(
            model_name='geodata',
            name='tweet_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Tweet',
        ),
        migrations.DeleteModel(
            name='TweetsPerDay',
        ),
    ]
