# Generated by Django 3.1.3 on 2021-01-28 12:27

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo_map', '0010_geocache'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeoLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('location_ids', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('density', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='geodata',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='geodata',
            name='longitude',
        ),
        migrations.AlterField(
            model_name='geocache',
            name='data_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None),
        ),
    ]
