# Generated by Django 3.1.3 on 2020-12-13 20:52

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo_map', '0010_geocache'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geocache',
            name='data_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None),
        ),
    ]
