# Generated by Django 3.1.3 on 2021-01-26 14:43

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geo_map', '0011_auto_20201213_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='geodata',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(default=None, null=True, srid=4326),
        ),
    ]
