# Generated by Django 3.1.3 on 2021-01-28 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geo_map', '0012_auto_20210128_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='geodata',
            name='geo_location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='geo_map.geolocation'),
            preserve_default=False,
        ),
    ]
