# Generated by Django 3.1.3 on 2021-01-29 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geo_map', '0014_remove_geodata_tweet_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geolocation',
            name='density',
        ),
        migrations.RemoveField(
            model_name='geolocation',
            name='location_ids',
        ),
    ]
