# Generated by Django 3.1.3 on 2021-01-31 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geo_map', '0015_auto_20210129_2204'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GeoData',
        ),
    ]
