# Generated by Django 3.1.3 on 2021-01-31 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geo_map', '0016_delete_geodata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geolocation',
            name='location',
        ),
    ]
