# Generated by Django 3.1.3 on 2020-12-08 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timedata',
            name='date',
            field=models.TextField(default=2013, max_length=11),
            preserve_default=False,
        ),
    ]
